name = "zaplex"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_Zm9uZC1iYWRnZXItNjUuY2xlcmsuYWNjb3VudHMuZGV2JA"

[[ d1_databases ]]
binding = "DB"
database_name = "zaplex"
database_id = "512628aa-7b50-4756-be63-3f15ac6230b6"